# Generated by Django 4.1 on 2023-03-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculadora", "0003_partidas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="partidas",
            name="fecha",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="partidas",
            name="id_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="calculadora.usuarios"
            ),
        ),
    ]
