# Generated by Django 4.1 on 2023-03-30 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculadora", "0004_usuarios_alter_partidas_fecha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partidas",
            name="id_usuario",
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name="Partida_Jugadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("minutos_jugados", models.IntegerField()),
                ("puntaje", models.IntegerField()),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculadora.usuarios",
                    ),
                ),
            ],
        ),
    ]
